### ISSUE TITLE
关于实验细节的问题

### ISSUE THREAD

**Issue by tymanman** [hzhupku/DCNet#1]
hi,
   最近阅读到你们投在cvpr2021关于few-shot的paper，"Dense Relation Distillation..."，觉得很赞。但是对其中一些实验细节比较困惑，希望不吝解答一下。

1.voc 上面的10 random runs是基于TFA的30个seed吗，然后取了topk10的seed结果吗
谢谢

**Comment by hzhupku** [comment]
We perform experiments under 10 random runs with different random seeds.
