### ISSUE TITLE
Training for voc2012

### ISSUE THREAD

**Issue by xiaofeng-c** [hzhupku/DCNet#13]
In your codes,i want to know if it just for voc2007 or i need to add some extra codes when use the voc2012 dataset?Because when i use the voc2012  to train,a error occur:
**FileNotFoundError: [Errno 2] No such file or directory: '/home/dl/VSST/zwm/DCNet-main/VOCdevkit/VOC2012/Annotations/000005.xml'**
as we know,the annotation of voc2012 datasets use the 'year_id.xml' format.Thank you for your answer.

**Comment by hzhupku** [comment]
No need for extra code for voc2012. But if you still have this problem, please feel free to reopen this issue.
