### ISSUE TITLE
Environmental issues of the project

### ISSUE THREAD

**Issue by wsjxdy** [hzhupku/DCNet#16]
I followed the install.md build environment to build four or five times, and every time I encountered ImportError:
*"/DCNet-main/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gpu.so:** undefined symbol: __cudaPopCallConfiguration"*. 
 But I am completely I installed it according to install.md. The cuda version of my computer is 9.0.176, and gcc tried 5.5 and 7.5, but they all reported the same error. What are the specific torch, cuda, torchvision, gcc and other environments you are using?  Why do I get an error following the installation tutorial? Looking forward to your quick reply! @hzhupku

**Comment by juliusyang97** [comment]
cuda和torch不匹配

**Comment by juliusyang97** [comment]
> cuda和torch不匹配

我用的cuda10.0，torch1.2.0，没问题，，，你这个问题应该是你的torch是cuda9.0版本的，但是你的cuda不是9.0

**Comment by LiangYang666** [comment]
建议使用docker创建环境来跑，很多东西都已经无法直接pip install到了，可以参考我的博客[docker跑通DCNet](https://blog.csdn.net/qq_39165617/article/details/121799374?spm=1001.2014.3001.5501)

**Comment by hzhupku** [comment]
The details are in the INSTALL.md.
