### ISSUE TITLE
 what is DCNet w/CFA?

### ISSUE THREAD

**Issue by buncybunny** [hzhupku/DCNet#2]
Hi.

I understand that “DCNet w/o CFA” is FasterRCNN with DRD only and “DCNet” is your network architecture, which is DRD+CFA. 

But what is “DCNet w/CFA”? 
It must be different from "DCNet"(DRD+CFA). There isn’t any description of this one.

**Comment by hzhupku** [comment]
DCNet w/CFA means DCNet without attention-based aggregation in CFA.
