### ISSUE TITLE
Details of method

### ISSUE THREAD

**Issue by ZhangGongjie** [hzhupku/DCNet#3]
Awesome work! But I have a minor question:

In page 4, you mentioned 

> Noted that there are N support features, which brings N key-value pairs. We perform summation over N output results to obtain the final result, which is a refined query feature, activated by support features where there are co-existing classes of objects in query and support images.

Could you please use mathematical equations to further clarify this?

**Comment by hzhupku** [comment]
Please check the code for more details. Feel free to re-open this issue if the problem is not resolved.
