### ISSUE TITLE
fair comparison?

### ISSUE THREAD

**Issue by Wei-i** [hzhupku/DCNet#6]
您好 首先非常感谢您的论文和开源代码。
我粗略看完文章后，发现您是meta-learning based FSOD，并且基于Meta R-CNN和FsDetView*的，但我有些疑惑，在Meta R-CNN代码repo下，很多人有提出issue，认为它们在比较时是不公平的。
在比较新的另一篇CVPR [2021的文章中][GFSD](https://openaccess.thecvf.com/content/CVPR2021/papers/Fan_Generalized_Few-Shot_Object_Detection_Without_Forgetting_CVPR_2021_paper.pdf) ，它们采用了相同的sample策略后，从文章中得出FsDetView（coco 10-shot）并不是12.5。
因此 我想问下您是基于它们原有的采样方法没有啥更改吗？

**Comment by sunnyykk** [comment]
> 您好 首先非常感谢您的论文和开源代码。
> 我粗略看完文章后，发现您是meta-learning based FSOD，并且基于Meta R-CNN和FsDetView*的，但我有些疑惑，在Meta R-CNN代码repo下，很多人有提出issue，认为它们在比较时是不公平的。
> 在比较新的另一篇CVPR [2021的文章中][GFSD](https://openaccess.thecvf.com/content/CVPR2021/papers/Fan_Generalized_Few-Shot_Object_Detection_Without_Forgetting_CVPR_2021_paper.pdf) ，它们采用了相同的sample策略后，从文章中得出FsDetView（coco 10-shot）并不是12.5。
> 因此 我想问下您是基于它们原有的采样方法没有啥更改吗？

碰巧今天刚看到这篇文章，我注意到4.1节最后有这么一句~
> Moreover, we implement it by ourselves for a more fair comparison.

不知能否回答~虽然我也不知道改了啥hhh

**Comment by Wei-i** [comment]
感谢您这么迟的回复。 是的是的 ，我也在GFSD的repo下提出了issue，作者也表明他们确实是重新用了采样策略。所以之前我很迷茫  我不确定是否 meta laearning based的方法是否真的存在不公平比较的现象(比如meta rcnn在第二阶段 一开始代码用了3*shot 造成不公平的比较。) 然后FsdetView这篇也有人在issue指出一些bug，不过作者也说了大部分模块是直接照搬Meta R-CNN。 
我目前刚刚接调研FSOD 这一块， 由于transfer learning baesd的(TFA  G FSD  FSCE ) 基本都是比较新的，基于detectron2的版本， 容易实现，我复现了一下效果都比较接近。 
我真的比较迷茫，不知道是相信transfer learning报的结果 还是 meta learning报的结果 :(。 
因此我还想冒昧地想问下 您实现是保证了10-shot 就是 novel 和base 都是10这种情况吗。 如果是的话那感觉12.8 应该是几篇新的里面最新的SOTA(除了一篇还没开源的Meta  DETR)  希望得到您的见解  谢谢!

**Comment by Wei-i** [comment]
> > 您好 首先非常感谢您的论文和开源代码。
> > 我粗略看完文章后，发现您是meta-learning based FSOD，并且基于Meta R-CNN和FsDetView*的，但我有些疑惑，在Meta R-CNN代码repo下，很多人有提出issue，认为它们在比较时是不公平的。
> > 在比较新的另一篇CVPR [2021的文章中][GFSD](https://openaccess.thecvf.com/content/CVPR2021/papers/Fan_Generalized_Few-Shot_Object_Detection_Without_Forgetting_CVPR_2021_paper.pdf) ，它们采用了相同的sample策略后，从文章中得出FsDetView（coco 10-shot）并不是12.5。
> > 因此 我想问下您是基于它们原有的采样方法没有啥更改吗？
> 
> 碰巧今天刚看到这篇文章，我注意到4.1节最后有这么一句~
> 
> > Moreover, we implement it by ourselves for a more fair comparison.
> 
> 不知能否回答~虽然我也不知道改了啥hhh

感谢您这么迟的回复。 是的是的 ，我也在GFSD的repo下提出了issue，作者也表明他们确实是重新用了采样策略。所以之前我很迷茫  我不确定是否 meta laearning based的方法是否真的存在不公平比较的现象(比如meta rcnn在第二阶段 一开始代码用了3*shot 造成不公平的比较。) 然后FsdetView这篇也有人在issue指出一些bug，不过作者也说了大部分模块是直接照搬Meta R-CNN。
我目前刚刚接调研FSOD 这一块， 由于transfer learning baesd的(TFA  G FSD  FSCE ) 基本都是比较新的，基于detectron2的版本， 容易实现，我复现了一下效果都比较接近。
我真的比较迷茫，不知道是相信transfer learning报的结果 还是 meta learning报的结果 :(。
因此我还想冒昧地想问下 您实现是保证了10-shot 就是 novel 和base 都是10这种情况吗。 如果是的话那感觉12.8 应该是几篇新的里面最新的SOTA(除了一篇还没开源的Meta  DETR)  希望得到您的见解  谢谢!

**Comment by hzhupku** [comment]
Thank you for your question. We implement the sampling strategy according to Meta YOLO (https://github.com/bingykang/Fewshot_Detection) rather than Meta R-CNN.

**Comment by sunnyykk** [comment]
> > > 您好 首先非常感谢您的论文和开源代码。
> > > 我粗略看完文章后，发现您是meta-learning based FSOD，并且基于Meta R-CNN和FsDetView*的，但我有些疑惑，在Meta R-CNN代码repo下，很多人有提出issue，认为它们在比较时是不公平的。
> > > 在比较新的另一篇CVPR [2021的文章中][GFSD](https://openaccess.thecvf.com/content/CVPR2021/papers/Fan_Generalized_Few-Shot_Object_Detection_Without_Forgetting_CVPR_2021_paper.pdf) ，它们采用了相同的sample策略后，从文章中得出FsDetView（coco 10-shot）并不是12.5。
> > > 因此 我想问下您是基于它们原有的采样方法没有啥更改吗？
> > 
> > 
> > 碰巧今天刚看到这篇文章，我注意到4.1节最后有这么一句~
> > > Moreover, we implement it by ourselves for a more fair comparison.
> > 
> > 
> > 不知能否回答~虽然我也不知道改了啥hhh
> 
> 感谢您这么迟的回复。 是的是的 ，我也在GFSD的repo下提出了issue，作者也表明他们确实是重新用了采样策略。所以之前我很迷茫 我不确定是否 meta laearning based的方法是否真的存在不公平比较的现象(比如meta rcnn在第二阶段 一开始代码用了3*shot 造成不公平的比较。) 然后FsdetView这篇也有人在issue指出一些bug，不过作者也说了大部分模块是直接照搬Meta R-CNN。
> 我目前刚刚接调研FSOD 这一块， 由于transfer learning baesd的(TFA G FSD FSCE ) 基本都是比较新的，基于detectron2的版本， 容易实现，我复现了一下效果都比较接近。
> 我真的比较迷茫，不知道是相信transfer learning报的结果 还是 meta learning报的结果 :(。
> 因此我还想冒昧地想问下 您实现是保证了10-shot 就是 novel 和base 都是10这种情况吗。 如果是的话那感觉12.8 应该是几篇新的里面最新的SOTA(除了一篇还没开源的Meta DETR) 希望得到您的见解 谢谢!

哈哈，已email您github主页邮箱~也想多多交流

**Comment by Wei-i** [comment]
> Thank you for your question. We implement the sampling strategy according to Meta YOLO (https://github.com/bingykang/Fewshot_Detection) rather than Meta R-CNN.

Thanks for your reply:)
