### ISSUE TITLE
plz check your code

### ISSUE THREAD

**Issue by Wei-i** [hzhupku/DCNet#7]
https://github.com/hzhupku/DCNet/blob/a73f448fc664d8c5aabf8b7b459942e8c576e6a6/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py#L47

**Comment by Wei-i** [comment]
https://github.com/hzhupku/DCNet/blob/a73f448fc664d8c5aabf8b7b459942e8c576e6a6/maskrcnn_benchmark/data/datasets/__init__.py#L9 
comment out this line

**Comment by Wei-i** [comment]
Another issue made me confused is that  how I can new a `DCNet/fs_list/voc_traindict_bbox_Xshot.txt` and  `DCNet/fs_list/voc_traindict_full.txt`  instead of  using the files you provide in which each line contains the absolute path.
When preparing voc_dataset, the dir is 'datasets/VOCdevkit/..', however when training, the `root_dir` is `datasets/voc/VOC{year}` and so on .
BTW, these made me feel  sad to reproduce by my poor ability.

**Comment by Wei-i** [comment]
voc_split_3_base_training:
<img width="1667" alt="421ef91b4147013b422cdbfcb1077fd" src="https://user-images.githubusercontent.com/47490392/131104178-d4d26db9-cd1b-4e63-b8dd-0febd7c34a21.png">

**Comment by Wei-i** [comment]
reproduce reuslt:
voc_split_1_10_shot:  58.9 vs 59.6(from the paper)
voc_split_2_10_shot:  44.9 vs 46.6(from the  paper)

**Comment by hzhupku** [comment]
Thank you for the reminder. I have updated the code.

**Comment by hzhupku** [comment]
For the performance in the paper, we report the results averaged over multiple random runs.
